label.titulo.pagina.consulta = Agendas Cadastradas
label.titulo.pagina.cadastro = Cadastro de Agendas
label.modal.titulo = Confirma\u00E7\u00E3o de Exclus\u00E3o
label.modal.corpo = Deseja realizar a Exclus\u00E3o da Agenda?