label.titulo.pagina.relatorio = Relat\u00F3rio de Compromissos por Per\u00EDodo
label.cod.funcionario = C\u00F3d. Funcion\u00E1rio
label.nome.funcionario = Nome Funcion\u00E1rio
label.cod.agenda = C\u00F3d. Agenda
label.nome.agenda = Nome Agenda